// Generated by scripts/extract-plan.py from BetterCalc_Demo_Apartment_A_Floor_Plan.pdf. Do not edit by hand.
// Geometry is 1:1 with the PDF (points, y flipped). Printed area numerals are intentionally omitted.
import { memo } from 'react'

export const PlanDrawing = memo(function PlanDrawing({ className = '' }: { className?: string }) {
  return (
    <svg className={`plan-drawing ${className}`.trim()} viewBox="0 0 1190.551 841.8898" aria-hidden="true" focusable="false">
      <g className="pd-layer pd-meta">
        <text x={52} y={46} fontSize={15} fontWeight={700} className="pd-text-ink">BETTERCALC DEMO</text>
        <text x={52} y={60} fontSize={8} className="pd-text-graphite">VECTOR QUANTITY-TAKEOFF SAMPLE / NOT FOR CONSTRUCTION</text>
        <path d="M52 72L1138.55 72" className="pd-stroke-rule" strokeWidth={0.8} />
        <path d="M1106.55 147L1106.55 104" className="pd-stroke-ink" strokeWidth={1} />
        <path d="M1106.55 95L1100.55 108L1112.55 108Z" className="pd-fs-ink" strokeWidth={1} />
        <text x={1103.66} y={90} fontSize={8} fontWeight={700} className="pd-text-ink">N</text>
        <path d="M974.55 797.89L1138.55 797.89L1138.55 705.89L974.55 705.89Z" className="pd-stroke-ink" strokeWidth={0.9} />
        <path d="M974.55 770.89L1138.55 770.89" className="pd-stroke-ink" strokeWidth={0.9} />
        <path d="M974.55 742.89L1138.55 742.89" className="pd-stroke-ink" strokeWidth={0.9} />
        <path d="M1078.55 797.89L1078.55 742.89" className="pd-stroke-ink" strokeWidth={0.9} />
        <text x={984.55} y={728.89} fontSize={10} fontWeight={700} className="pd-text-ink">BETTERCALC DEMO</text>
        <text x={984.55} y={756.89} fontSize={8} className="pd-text-ink">APARTMENT A</text>
        <text x={984.55} y={785.89} fontSize={9} fontWeight={700} className="pd-text-ink">FLOOR PLAN</text>
        <text x={1086.55} y={756.89} fontSize={8} className="pd-text-ink">A-101</text>
        <text x={1086.55} y={785.89} fontSize={8} className="pd-text-ink">SCALE 1:100</text>
        <text x={52} y={812.89} fontSize={6.5} className="pd-text-graphite">DEMONSTRATION DRAWING. ALL DIMENSIONS IN METRES. VERIFY CALIBRATION USING THE 5.00 m REFERENCE.</text>
      </g>
      <g className="pd-layer pd-fixtures">
        <path d="M638 750.09L958 750.09L958 650.89L638 650.89Z" className="pd-stroke-graphite" strokeWidth={1} />
        <path d="M643.12 743.69L952.88 743.69" className="pd-stroke-graphite" strokeWidth={1.4} />
        <path d="M647.6 743.69L647.6 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M702 743.69L702 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M756.4 743.69L756.4 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M810.8 743.69L810.8 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M865.2 743.69L865.2 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M919.6 743.69L919.6 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M948.4 743.69L948.4 732.81" className="pd-stroke-soft" strokeWidth={0.55} />
        <path d="M538.8 186.89L702 186.89L702 154.89L538.8 154.89Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M538.8 286.09L570.8 286.09L570.8 186.89L538.8 186.89Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M590 250.89L689.2 250.89L689.2 211.21L590 211.21Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M661.04 177.93C661.04 176.16 659.61 174.73 657.84 174.73C656.07 174.73 654.64 176.16 654.64 177.93C654.64 179.7 656.07 181.13 657.84 181.13C659.61 181.13 661.04 179.7 661.04 177.93" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M661.04 165.13C661.04 163.36 659.61 161.93 657.84 161.93C656.07 161.93 654.64 163.36 654.64 165.13C654.64 166.9 656.07 168.33 657.84 168.33C659.61 168.33 661.04 166.9 661.04 165.13" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M673.84 177.93C673.84 176.16 672.41 174.73 670.64 174.73C668.87 174.73 667.44 176.16 667.44 177.93C667.44 179.7 668.87 181.13 670.64 181.13C672.41 181.13 673.84 179.7 673.84 177.93" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M673.84 165.13C673.84 163.36 672.41 161.93 670.64 161.93C668.87 161.93 667.44 163.36 667.44 165.13C667.44 166.9 668.87 168.33 670.64 168.33C672.41 168.33 673.84 166.9 673.84 165.13" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M545.2 247.69L564.4 247.69L564.4 212.49L545.2 212.49Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M406.32 212.49L463.92 212.49L463.92 154.89L406.32 154.89Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M406.32 212.49L463.92 154.89" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M437.12 183.69C437.12 182.59 436.22 181.69 435.12 181.69C434.02 181.69 433.12 182.59 433.12 183.69C433.12 184.79 434.02 185.69 435.12 185.69C436.22 185.69 437.12 184.79 437.12 183.69" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M503.6 164.49L480.56 164.49L480.56 178.57L503.6 178.57Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M477.36 193.61C477.36 202.27 483.95 209.29 492.08 209.29C500.21 209.29 506.8 202.27 506.8 193.61C506.8 184.95 500.21 177.93 492.08 177.93C483.95 177.93 477.36 184.95 477.36 193.61" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M450.8 257.29L486 257.29L486 231.69L450.8 231.69Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M476.08 244.49C476.08 241.31 472.64 238.73 468.4 238.73C464.16 238.73 460.72 241.31 460.72 244.49C460.72 247.67 464.16 250.25 468.4 250.25C472.64 250.25 476.08 247.67 476.08 244.49" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M535.6 634.89L590 634.89L590 580.49L535.6 580.49Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M535.6 634.89L590 580.49" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M564.8 607.69C564.8 606.59 563.9 605.69 562.8 605.69C561.7 605.69 560.8 606.59 560.8 607.69C560.8 608.79 561.7 609.69 562.8 609.69C563.9 609.69 564.8 608.79 564.8 607.69" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M639.92 586.89L616.88 586.89L616.88 600.97L639.92 600.97Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M613.68 616.01C613.68 624.67 620.27 631.69 628.4 631.69C636.53 631.69 643.12 624.67 643.12 616.01C643.12 607.35 636.53 600.33 628.4 600.33C620.27 600.33 613.68 607.35 613.68 616.01" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M572.4 545.29L607.6 545.29L607.6 519.69L572.4 519.69Z" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M597.68 532.49C597.68 529.31 594.24 526.73 590 526.73C585.76 526.73 582.32 529.31 582.32 532.49C582.32 535.67 585.76 538.25 590 538.25C594.24 538.25 597.68 535.67 597.68 532.49" className="pd-stroke-graphite" strokeWidth={0.8} />
        <path d="M158.8 314.89L278.8 314.89C281.01 314.89 282.8 313.1 282.8 310.89L282.8 184.49C282.8 182.28 281.01 180.49 278.8 180.49L158.8 180.49C156.59 180.49 154.8 182.28 154.8 184.49L154.8 310.89C154.8 313.1 156.59 314.89 158.8 314.89Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M154.8 218.12L282.8 218.12" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M162.92 212.75L210.68 212.75C212.34 212.75 213.68 211.4 213.68 209.75L213.68 193.35C213.68 191.69 212.34 190.35 210.68 190.35L162.92 190.35C161.26 190.35 159.92 191.69 159.92 193.35L159.92 209.75C159.92 211.4 161.26 212.75 162.92 212.75Z" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M226.92 212.75L274.68 212.75C276.34 212.75 277.68 211.4 277.68 209.75L277.68 193.35C277.68 191.69 276.34 190.35 274.68 190.35L226.92 190.35C225.26 190.35 223.92 191.69 223.92 193.35L223.92 209.75C223.92 211.4 225.26 212.75 226.92 212.75Z" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M165.2 622.09L250 622.09C252.21 622.09 254 620.3 254 618.09L254 498.09C254 495.88 252.21 494.09 250 494.09L165.2 494.09C162.99 494.09 161.2 495.88 161.2 498.09L161.2 618.09C161.2 620.3 162.99 622.09 165.2 622.09Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M161.2 529.93L254 529.93" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M169.32 524.81L245.88 524.81C247.54 524.81 248.88 523.47 248.88 521.81L248.88 505.41C248.88 503.75 247.54 502.41 245.88 502.41L169.32 502.41C167.66 502.41 166.32 503.75 166.32 505.41L166.32 521.81C166.32 523.47 167.66 524.81 169.32 524.81Z" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M363.6 622.09L448.4 622.09C450.61 622.09 452.4 620.3 452.4 618.09L452.4 498.09C452.4 495.88 450.61 494.09 448.4 494.09L363.6 494.09C361.39 494.09 359.6 495.88 359.6 498.09L359.6 618.09C359.6 620.3 361.39 622.09 363.6 622.09Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M359.6 529.93L452.4 529.93" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M367.72 524.81L444.28 524.81C445.94 524.81 447.28 523.47 447.28 521.81L447.28 505.41C447.28 503.75 445.94 502.41 444.28 502.41L367.72 502.41C366.06 502.41 364.72 503.75 364.72 505.41L364.72 521.81C364.72 523.47 366.06 524.81 367.72 524.81Z" className="pd-stroke-soft" strokeWidth={0.65} />
        <path d="M719.6 586.89L870 586.89C874.42 586.89 878 583.31 878 578.89L878 537.29C878 532.87 874.42 529.29 870 529.29L719.6 529.29C715.18 529.29 711.6 532.87 711.6 537.29L711.6 578.89C711.6 583.31 715.18 586.89 719.6 586.89Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M778 506.89L830.8 506.89C837.43 506.89 842.8 501.52 842.8 494.89L842.8 477.29C842.8 470.66 837.43 465.29 830.8 465.29L778 465.29C771.37 465.29 766 470.66 766 477.29L766 494.89C766 501.52 771.37 506.89 778 506.89Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M883.2 583.69L908 583.69C909.11 583.69 910 582.8 910 581.69L910 432.09C910 430.98 909.11 430.09 908 430.09L883.2 430.09C882.09 430.09 881.2 430.98 881.2 432.09L881.2 581.69C881.2 582.8 882.09 583.69 883.2 583.69Z" className="pd-stroke-soft" strokeWidth={0.8} />
        <path d="M786 260.49L874 260.49C876.21 260.49 878 258.7 878 256.49L878 214.57C878 212.36 876.21 210.57 874 210.57L786 210.57C783.79 210.57 782 212.36 782 214.57L782 256.49C782 258.7 783.79 260.49 786 260.49Z" className="pd-stroke-soft" strokeWidth={0.8} />
      </g>
      <g className="pd-layer pd-walls">
        <path d="M126 659.85L958 659.85L958 641.93L126 641.93Z" className="pd-fill-ink" />
        <path d="M126 147.85L958 147.85L958 129.93L126 129.93Z" className="pd-fill-ink" />
        <path d="M117.04 650.89L134.96 650.89L134.96 138.89L117.04 138.89Z" className="pd-fill-ink" />
        <path d="M949.04 650.89L966.96 650.89L966.96 138.89L949.04 138.89Z" className="pd-fill-ink" />
        <path d="M126 361.61L522.8 361.61L522.8 351.37L126 351.37Z" className="pd-fill-ink" />
        <path d="M325.68 650.89L335.92 650.89L335.92 356.49L325.68 356.49Z" className="pd-fill-ink" />
        <path d="M389.68 356.49L399.92 356.49L399.92 138.89L389.68 138.89Z" className="pd-fill-ink" />
        <path d="M517.68 650.89L527.92 650.89L527.92 138.89L517.68 138.89Z" className="pd-fill-ink" />
        <path d="M394.8 272.01L522.8 272.01L522.8 261.77L394.8 261.77Z" className="pd-fill-ink" />
        <path d="M522.8 508.81L663.6 508.81L663.6 498.57L522.8 498.57Z" className="pd-fill-ink" />
        <path d="M658.48 650.89L668.72 650.89L668.72 503.69L658.48 503.69Z" className="pd-fill-ink" />
        <path d="M522.8 310.41L958 310.41L958 300.17L522.8 300.17Z" className="pd-fill-ink" />
        <path d="M716.08 305.29L726.32 305.29L726.32 138.89L716.08 138.89Z" className="pd-fill-ink" />
        <path d="M193.2 367.37L247.6 367.37L247.6 345.61L193.2 345.61Z" className="pd-fill-ko" />
        <path d="M378.8 367.37L433.2 367.37L433.2 345.61L378.8 345.61Z" className="pd-fill-ko" />
        <path d="M319.92 570.89L341.68 570.89L341.68 516.49L319.92 516.49Z" className="pd-fill-ko" />
        <path d="M383.92 330.89L405.68 330.89L405.68 276.49L383.92 276.49Z" className="pd-fill-ko" />
        <path d="M383.92 366.09L405.68 366.09L405.68 329.61L383.92 329.61Z" className="pd-fill-ko" />
        <path d="M511.92 340.49L533.68 340.49L533.68 286.09L511.92 286.09Z" className="pd-fill-ko" />
        <path d="M433.2 277.77L481.2 277.77L481.2 256.01L433.2 256.01Z" className="pd-fill-ko" />
        <path d="M511.92 609.29L533.68 609.29L533.68 561.29L511.92 561.29Z" className="pd-fill-ko" />
        <path d="M652.72 609.29L674.48 609.29L674.48 558.09L652.72 558.09Z" className="pd-fill-ko" />
        <path d="M769.2 316.17L830 316.17L830 294.41L769.2 294.41Z" className="pd-fill-ko" />
        <path d="M878 149.77L938.8 149.77L938.8 128.01L878 128.01Z" className="pd-fill-ko" />
        <path d="M115.12 596.49L136.88 596.49L136.88 506.89L115.12 506.89Z" className="pd-fill-ko" />
        <path d="M123.12 596.49L123.12 506.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M128.88 596.49L128.88 506.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M117.68 596.49L134.32 596.49" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M117.68 506.89L134.32 506.89" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M115.12 295.69L136.88 295.69L136.88 202.89L115.12 202.89Z" className="pd-fill-ko" />
        <path d="M123.12 295.69L123.12 202.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M128.88 295.69L128.88 202.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M117.68 295.69L134.32 295.69" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M117.68 202.89L134.32 202.89" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M199.6 149.77L276.4 149.77L276.4 128.01L199.6 128.01Z" className="pd-fill-ko" />
        <path d="M199.6 141.77L276.4 141.77" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M199.6 136.01L276.4 136.01" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M199.6 147.21L199.6 130.57" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M276.4 147.21L276.4 130.57" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M564.4 149.77L654 149.77L654 128.01L564.4 128.01Z" className="pd-fill-ko" />
        <path d="M564.4 141.77L654 141.77" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M564.4 136.01L654 136.01" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M564.4 147.21L564.4 130.57" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M654 147.21L654 130.57" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M947.12 586.89L968.88 586.89L968.88 490.89L947.12 490.89Z" className="pd-fill-ko" />
        <path d="M955.12 586.89L955.12 490.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M960.88 586.89L960.88 490.89" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M949.68 586.89L966.32 586.89" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M949.68 490.89L966.32 490.89" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M947.12 455.69L968.88 455.69L968.88 353.29L947.12 353.29Z" className="pd-fill-ko" />
        <path d="M955.12 455.69L955.12 353.29" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M960.88 455.69L960.88 353.29" className="pd-stroke-ink" strokeWidth={1.15} />
        <path d="M949.68 455.69L966.32 455.69" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M949.68 353.29L966.32 353.29" className="pd-stroke-ink" strokeWidth={0.7} />
        <path d="M702 664.33L913.2 664.33L913.2 637.45L702 637.45Z" className="pd-fill-ko" />
        <path d="M702 658.57L702 643.21" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M807.6 658.57L807.6 643.21" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M913.2 658.57L913.2 643.21" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M702 654.09L913.2 654.09" className="pd-stroke-ink" strokeWidth={1.2} />
        <path d="M702 647.69L913.2 647.69" className="pd-stroke-ink" strokeWidth={1.2} />
      </g>
      <g className="pd-layer pd-labels">
        <text x={775.75} y={700.81} fontSize={9} fontWeight={700} className="pd-text-ink">BALCONY</text>
        <text x={214.22} y={193.29} fontSize={9.5} fontWeight={700} className="pd-text-ink">MASTER BEDROOM</text>
        <text x={199.63} y={430.09} fontSize={9.5} fontWeight={700} className="pd-text-ink">BEDROOM 1</text>
        <text x={398.03} y={430.09} fontSize={9.5} fontWeight={700} className="pd-text-ink">BEDROOM 2</text>
        <text x={419.33} y={227.21} fontSize={7.6} fontWeight={700} className="pd-text-ink">MASTER BATHROOM</text>
        <text x={437.55} y={304.01} fontSize={8.5} fontWeight={700} className="pd-text-ink">HALLWAY</text>
        <text x={568.18} y={545.29} fontSize={8.5} fontWeight={700} className="pd-text-ink">BATHROOM</text>
        <text x={600.89} y={199.69} fontSize={9.5} fontWeight={700} className="pd-text-ink">KITCHEN</text>
        <text x={773.82} y={378.89} fontSize={11} fontWeight={700} className="pd-text-ink">LIVING ROOM</text>
        <text x={815.99} y={195.21} fontSize={8.5} fontWeight={700} className="pd-text-ink">ENTRANCE</text>
      </g>
      <g className="pd-layer pd-dims">
        <path d="M126 114.57L330.8 114.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M126 117.57L126 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M330.8 117.57L330.8 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M126 111.57L126 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M330.8 111.57L330.8 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M212.94 119.57L243.86 119.57L243.86 107.57L212.94 107.57Z" className="pd-fill-ko" />
        <text x={216.94} y={117.07} fontSize={7.5} className="pd-text-ink">3.20 m</text>
        <path d="M330.8 114.57L522.8 114.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M330.8 117.57L330.8 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M522.8 117.57L522.8 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M330.8 111.57L330.8 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M522.8 111.57L522.8 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M411.34 119.57L442.26 119.57L442.26 107.57L411.34 107.57Z" className="pd-fill-ko" />
        <text x={415.34} y={117.07} fontSize={7.5} className="pd-text-ink">3.00 m</text>
        <path d="M522.8 114.57L721.2 114.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M522.8 117.57L522.8 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M721.2 117.57L721.2 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M522.8 111.57L522.8 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M721.2 111.57L721.2 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M606.54 119.57L637.46 119.57L637.46 107.57L606.54 107.57Z" className="pd-fill-ko" />
        <text x={610.54} y={117.07} fontSize={7.5} className="pd-text-ink">3.10 m</text>
        <path d="M721.2 114.57L958 114.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M721.2 117.57L721.2 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M958 117.57L958 111.57" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M721.2 111.57L721.2 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M958 111.57L958 131.21" className="pd-stroke-graphite" strokeWidth={0.45} />
        <path d="M824.14 119.57L855.06 119.57L855.06 107.57L824.14 107.57Z" className="pd-fill-ko" />
        <text x={828.14} y={117.07} fontSize={7.5} className="pd-text-ink">3.70 m</text>
        <path d="M95.28 650.89L95.28 138.89" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M91.28 650.89L99.28 650.89" className="pd-stroke-graphite" strokeWidth={0.65} />
        <path d="M91.28 138.89L99.28 138.89" className="pd-stroke-graphite" strokeWidth={0.65} />
        <text x={91.28} y={406.35} fontSize={7.5} className="pd-text-ink" transform="rotate(-90 91.28 406.35)">8.00 m</text>
      </g>
      <g className="pd-layer pd-reference">
        <path d="M177.2 773.77L497.2 773.77" className="pd-stroke-ink" strokeWidth={1.4} />
        <path d="M177.2 778.77L177.2 768.77" className="pd-stroke-ink" strokeWidth={1.4} />
        <path d="M497.2 778.77L497.2 768.77" className="pd-stroke-ink" strokeWidth={1.4} />
        <path d="M317.63 778.77L356.76 778.77L356.76 766.77L317.63 766.77Z" className="pd-fill-ko" />
        <text x={321.63} y={776.27} fontSize={10} fontWeight={700} className="pd-text-ink">5.00 m</text>
        <path d="M181.4 773.77C181.4 771.45 179.52 769.57 177.2 769.57C174.88 769.57 173 771.45 173 773.77C173 776.09 174.88 777.97 177.2 777.97C179.52 777.97 181.4 776.09 181.4 773.77" className="pd-fs-ko" strokeWidth={1.4} />
        <path d="M501.4 773.77C501.4 771.45 499.52 769.57 497.2 769.57C494.88 769.57 493 771.45 493 773.77C493 776.09 494.88 777.97 497.2 777.97C499.52 777.97 501.4 776.09 501.4 773.77" className="pd-fs-ko" strokeWidth={1.4} />
        <path d="M171.2 773.77L183.2 773.77" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M177.2 779.77L177.2 767.77" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M491.2 773.77L503.2 773.77" className="pd-stroke-ink" strokeWidth={0.8} />
        <path d="M497.2 779.77L497.2 767.77" className="pd-stroke-ink" strokeWidth={0.8} />
        <text x={262.62} y={757.13} fontSize={7.5} fontWeight={700} className="pd-text-graphite">REFERENCE DIMENSION - CALIBRATION</text>
      </g>
    </svg>
  )
})
