"""Read the real QTO Excel export and emit the data the site's Excel excerpt renders.

Usage: python3 scripts/extract-xlsx.py > src/data/qtoWorkbook.ts
Source: assets-source/reports/qto-quantities.xlsx (exported by BetterCalc). Nothing is hand-typed.
"""
import json, re, sys, zipfile
from html import unescape
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / 'assets-source/reports/qto-quantities.xlsx'
z = zipfile.ZipFile(SRC)
shared = [unescape(re.sub(r'<[^>]+>', '', m)) for m in re.findall(r'<si>(.*?)</si>', z.read('xl/sharedStrings.xml').decode('utf8'), re.S)]
workbook = z.read('xl/workbook.xml').decode('utf8')
sheet_names = [unescape(n) for n in re.findall(r'<sheet [^>]*name="([^"]+)"', workbook)]

def read_sheet(n):
    xml = z.read(f'xl/worksheets/sheet{n}.xml').decode('utf8')
    cells = {}
    for ref, attrs, inner in re.findall(r'<c r="([A-Z]+\d+)"([^>]*?)(?:/>|>(.*?)</c>)', xml, re.S):
        v = re.search(r'<v>(.*?)</v>', inner or '')
        t = re.search(r'<t[^>]*>(.*?)</t>', inner or '')
        value = shared[int(v.group(1))] if v and 't="s"' in attrs else (v.group(1) if v else (unescape(t.group(1)) if t else ''))
        if value != '':
            cells[ref] = value
    return cells

sheets = [{'name': name, 'cells': read_sheet(i + 1)} for i, name in enumerate(sheet_names)]
print('// Generated by scripts/extract-xlsx.py from assets-source/reports/qto-quantities.xlsx. Do not edit by hand.')
print(f'export const WORKBOOK_FILE = {json.dumps(SRC.name)}')
print(f'export const WORKBOOK_SHEETS: {{ name: string; cells: Record<string, string> }}[] = {json.dumps(sheets, ensure_ascii=False, indent=2)}')
